### ISSUE TITLE
NullReferenceException on VS start

### ISSUE THREAD

**Issue by i0n0s** [paiden/Edizen#1]
When starting Visual Studio, a message about an exception occured. The log list the following:
<entry>
    <record>701</record>
    <time>2019/07/10 06:32:07.282</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.
   at privatedeveloperinc.Edizen.KeepCentered.Align()
   at privatedeveloperinc.Edizen.KeepCentered.HandleCaretPositionChanged(Object sender, CaretPositionChangedEventArgs _)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
    </description>
  </entry>

Visual Studio 15.9.14 and before.
Edizen 1.4.0

The exception didn't occured with 1.3.0.

Thanks for fixing.

**Comment by paiden** [comment]
Should be fixed with v1.4.1.
